[package]
name = "game-of-life"
version = "0.1.0"
edition = "2018"

[dependencies]
piston = "0.48.0"
piston2d-graphics = "0.32.0"
pistoncore-glutin_window = "0.61.0"
piston2d-opengl_graphics = "0.65.0"
rand = "0.7.0"

